version: 0.2

env:
  variables:
    GIT_USER: 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
    GIT_PASSWORD: maan338
    test: t
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - git config --global credential.helper store --replace-all
      - git config -l
      - echo "https://$GIT_USER:$GIT_PASSWORD@github.com " > ~/.git-credentials
      - cat /root/.gitconfig
      #- git clone https://github.com/maan338/nuget-package-sample.git
      #- git clone https://github.com/XXXXX/YYYY.git
      - echo "sample" > sample.sample
      - git init
      - git config --global user.email "${GIT_EMAIL}"
      - git config --global user.name "{$GIT_USER}"
      - git config pull.rebase true
      #- git remote add origin https://github.com/XXXX/YYYY.git
      - git remote add origin https://github.com/maan338/test1.git
      - git pull origin master
      - git add * 
      - git stash
      - echo ${RANDOM:0:9} > rand.txt
      - git add .
      - git commit -am "rand new"
      - git branch -M master
      - git push --set-upstream origin master

      #- git config --global --unset credential.helper
      #- git config --global credential.helper store
      #- echo "https://$GIT_USER:$GIT_PASSWORD@github.com " > ~/.git-credentials
      #- cat /root/.gitconfig
      #- git init
      #- echo hi > hi.mom
      #- git add .
      #- git commit -am "hi mom"
      #- git branch -M master
      #- git remote add origin https://github.com/maan338/pushere.git
      #- git remote add origin "https://{$MY_GIT_USER}:{$MY_GIT_TOKEN}@github.com/{$MY_GIT_USER}/project.git"
      #- git push -u origin master
      - python setup.py pytest
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
    - 'template.yml'
    - 'scripts/**/*'
    - 'helloworld/**/*.py'
    - 'appspec.yml'
    - 'requirements.txt'
    - 'setup.py'
    - 'template-configuration.json'
